import { state } from "../state.js";
import { showToast } from "../ui.js";

export function loadSettings() { try { const e = JSON.parse(localStorage.getItem("jarvis-settings") || "{}"); state.endpoint = e.endpoint || "http://127.0.0.1:11434"; state.temperature = e.temperature ?? .7; state.ttsEnabled = e.ttsEnabled ?? !0; state.speechRate = e.speechRate ?? 1; state.speechPitch = e.speechPitch ?? 1; state.contextWindow = e.contextWindow ?? 20; if (e.model) { state.model = e.model; $activeModelLabel && ($activeModelLabel.textContent = state.model); $pModel && ($pModel.textContent = state.model); } else { state.model = "llama3.1:8b"; $activeModelLabel && ($activeModelLabel.textContent = state.model); $pModel && ($pModel.textContent = state.model); setTimeout(async () => { try { /* CSP FIX: replaced direct fetch() with IPC-proxied ollamaFetch */ const res = await window.jarvis.ollamaFetch({ path: '/api/tags', method: 'GET' }); if (res && res.ok) { const data = JSON.parse(res.body); if (data.models && data.models.length > 0) { const detected = data.models[0].name; state.model = detected; $activeModelLabel && ($activeModelLabel.textContent = state.model); $pModel && ($pModel.textContent = state.model); const n = JSON.parse(localStorage.getItem("jarvis-settings") || "{}"); n.model = detected; localStorage.setItem("jarvis-settings", JSON.stringify(n)); showToast("Auto-detected LLM: " + detected, "success"); } } } catch (err) { } }, 1500); } if (e.theme && THEMES[e.theme]) { const t = THEMES[e.theme]; state.theme = e.theme; t.attr ? document.documentElement.setAttribute("data-theme", t.attr) : document.documentElement.removeAttribute("data-theme"); requestAnimationFrame(() => { document.querySelectorAll(".theme-swatch").forEach(n => { const s = n.id.replace("cfg-theme-", "").replace("ham-theme-", ""); n.classList.toggle("active", s === e.theme) }) }) } } catch { } }

window.loadSettings = loadSettings;

export function saveSettings() { state.model = document.getElementById("cfg-model").value, state.endpoint = document.getElementById("cfg-endpoint").value.trim() || "http://127.0.0.1:11434", state.temperature = parseFloat(document.getElementById("cfg-temperature").value), state.ttsEnabled = document.getElementById("cfg-tts").checked, state.speechRate = parseFloat(document.getElementById("cfg-speech-rate").value), state.speechPitch = parseFloat(document.getElementById("cfg-speech-pitch").value), state.contextWindow = parseInt(document.getElementById("cfg-context").value), localStorage.setItem("jarvis-settings", JSON.stringify({ model: state.model, endpoint: state.endpoint, temperature: state.temperature, ttsEnabled: state.ttsEnabled, speechRate: state.speechRate, speechPitch: state.speechPitch, contextWindow: state.contextWindow, theme: state.theme || "ironman" })), $activeModelLabel && ($activeModelLabel.textContent = state.model), $pModel && ($pModel.textContent = state.model), $ttsBtn && $ttsBtn.classList.toggle("active", state.ttsEnabled), document.querySelectorAll(".model-preset-btn").forEach(e => { const t = e.getAttribute("onclick")?.match(/'([^']+)'/); e.classList.toggle("active", t && t[1] === state.model) }), closeModal("settings-modal"), showToast("Configuration saved, sir.", "success"), checkOllama() }

window.saveSettings = saveSettings;

export function applyTheme(e) { const t = THEMES[e] || THEMES.ironman; state.theme = e, t.attr ? document.documentElement.setAttribute("data-theme", t.attr) : document.documentElement.removeAttribute("data-theme"), document.querySelectorAll(".theme-swatch").forEach(n => { const s = n.id.replace("cfg-theme-", "").replace("ham-theme-", ""); n.classList.toggle("active", s === e) }); try { const n = JSON.parse(localStorage.getItem("jarvis-settings") || "{}"); n.theme = e, localStorage.setItem("jarvis-settings", JSON.stringify(n)) } catch { } showToast("Theme: " + t.label, "info") }

window.applyTheme = applyTheme;

export function resetSettings() { localStorage.removeItem("jarvis-settings"), window.loadSettings(), populateSettingsModal(), showToast("Defaults restored.", "info") }

window.resetSettings = resetSettings;

export function populateSettingsModal() { const e = document.getElementById("cfg-model"); if (e) { let t = !1; for (const n of e.options) if (n.value === state.model) { t = !0; break } if (!t) { const n = document.createElement("option"); n.value = state.model, n.textContent = state.model + "  (custom)", e.appendChild(n) } e.value = state.model } document.getElementById("cfg-endpoint").value = state.endpoint, document.getElementById("cfg-temperature").value = state.temperature, document.getElementById("cfg-temp-val").textContent = state.temperature.toFixed(2), document.getElementById("cfg-tts").checked = state.ttsEnabled, document.getElementById("cfg-speech-rate").value = state.speechRate, document.getElementById("cfg-rate-val").textContent = `${state.speechRate.toFixed(1)}\xD7`, document.getElementById("cfg-speech-pitch").value = state.speechPitch, document.getElementById("cfg-pitch-val").textContent = state.speechPitch.toFixed(1), document.getElementById("cfg-context").value = state.contextWindow, document.getElementById("cfg-temperature").oninput = t => { document.getElementById("cfg-temp-val").textContent = parseFloat(t.target.value).toFixed(2) }, document.getElementById("cfg-speech-rate").oninput = t => { document.getElementById("cfg-rate-val").textContent = `${parseFloat(t.target.value).toFixed(1)}\xD7` }, document.getElementById("cfg-speech-pitch").oninput = t => { document.getElementById("cfg-pitch-val").textContent = parseFloat(t.target.value).toFixed(1) }, document.querySelectorAll(".model-preset-btn").forEach(t => { const n = t.getAttribute("onclick")?.match(/'([^']+)'/); t.classList.toggle("active", n && n[1] === state.model) }) }

window.populateSettingsModal = populateSettingsModal;

